"""restart all migrations

Revision ID: 032d04bd6c3f
Revises: 
Create Date: 2023-04-05 22:27:23.497505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032d04bd6c3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('my_review', sa.String(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('favourite', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('colour', sa.String(), nullable=True),
    sa.Column('taste', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('game_genres_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['game_genres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_genres_association_id'), 'game_genres_association', ['id'], unique=False)
    op.create_table('game_screenshots',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_screenshots')
    op.drop_index(op.f('ix_game_genres_association_id'), table_name='game_genres_association')
    op.drop_table('game_genres_association')
    op.drop_table('pickles')
    op.drop_table('games')
    op.drop_table('game_genres')
    # ### end Alembic commands ###
