"""make table pickles

Revision ID: 70cb55c736e3
Revises: 8ac6c5b0b1ce
Create Date: 2023-04-03 18:02:35.677644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70cb55c736e3'
down_revision = '8ac6c5b0b1ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('colour', sa.String(), nullable=True),
    sa.Column('taste', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pickles')
    # ### end Alembic commands ###
