"""screenshots associated with game get cascade deleted now

Revision ID: c9c9efdf2f19
Revises: 032d04bd6c3f
Create Date: 2023-04-05 23:15:37.651661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c9efdf2f19'
down_revision = '032d04bd6c3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
